services:

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api-examenes.aranadev.com
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-cambia_este_secreto_jwt_32_chars}
      DATABASE_URL: postgres://postgres:password@db:5432/examenes
      CORS_ORIGINS: https://examenes.aranadev.com,https://www.examenes.aranadev.com
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: examenes
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
